// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsy7_yr43-hQKqo0AxB1ba4bbWdoUQ8vw',
    appId: '1:173252372729:web:e7d410aaaddfb9838bda28',
    messagingSenderId: '173252372729',
    projectId: 'nails-bussiness-clientlist',
    authDomain: 'nails-bussiness-clientlist.firebaseapp.com',
    storageBucket: 'nails-bussiness-clientlist.firebasestorage.app',
    measurementId: 'G-DW003ZJT4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAlZNlnpWPfvHhnKlVw1907KSnuFasgOU',
    appId: '1:173252372729:android:b57fd5ca8745c8858bda28',
    messagingSenderId: '173252372729',
    projectId: 'nails-bussiness-clientlist',
    storageBucket: 'nails-bussiness-clientlist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOPKtbZ1xH6ZKApqT5uHiZyFDme7qYNNE',
    appId: '1:173252372729:ios:408c7462891847cf8bda28',
    messagingSenderId: '173252372729',
    projectId: 'nails-bussiness-clientlist',
    storageBucket: 'nails-bussiness-clientlist.firebasestorage.app',
    iosBundleId: 'com.example.nailclientapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOPKtbZ1xH6ZKApqT5uHiZyFDme7qYNNE',
    appId: '1:173252372729:ios:408c7462891847cf8bda28',
    messagingSenderId: '173252372729',
    projectId: 'nails-bussiness-clientlist',
    storageBucket: 'nails-bussiness-clientlist.firebasestorage.app',
    iosBundleId: 'com.example.nailclientapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsy7_yr43-hQKqo0AxB1ba4bbWdoUQ8vw',
    appId: '1:173252372729:web:df50cfb8f8fe306b8bda28',
    messagingSenderId: '173252372729',
    projectId: 'nails-bussiness-clientlist',
    authDomain: 'nails-bussiness-clientlist.firebaseapp.com',
    storageBucket: 'nails-bussiness-clientlist.firebasestorage.app',
    measurementId: 'G-MJCPGSWR8B',
  );
}
